services:
  - type: web
    name: whatsapp-chat-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free
    branch: main
    autoDeploy: true
